app:
  bootstrap-admin:
    enabled: true
    username: admin
    password: "admin@123"
    full-name: "System Administrator"

logging:
  level:
    "[com.attendance]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE
